# Generated by Django 4.0.1 on 2022-02-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VanbrodskiMotori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('jacina', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
